// Code generated by protoc-gen-go. DO NOT EDIT.
// source: summarizer/summarizer.proto

/*
Package summarizer is a generated protocol buffer package.

It is generated from these files:
	summarizer/summarizer.proto

It has these top-level messages:
	SummarizerRequest
	Summary
*/
package summarizer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SummarizerRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *SummarizerRequest) Reset()                    { *m = SummarizerRequest{} }
func (m *SummarizerRequest) String() string            { return proto.CompactTextString(m) }
func (*SummarizerRequest) ProtoMessage()               {}
func (*SummarizerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SummarizerRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Summary struct {
	Tags []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
}

func (m *Summary) Reset()                    { *m = Summary{} }
func (m *Summary) String() string            { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()               {}
func (*Summary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Summary) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*SummarizerRequest)(nil), "summarizer.SummarizerRequest")
	proto.RegisterType((*Summary)(nil), "summarizer.Summary")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SummarizerService service

type SummarizerServiceClient interface {
	Summarize(ctx context.Context, in *SummarizerRequest, opts ...grpc.CallOption) (*Summary, error)
}

type summarizerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSummarizerServiceClient(cc *grpc.ClientConn) SummarizerServiceClient {
	return &summarizerServiceClient{cc}
}

func (c *summarizerServiceClient) Summarize(ctx context.Context, in *SummarizerRequest, opts ...grpc.CallOption) (*Summary, error) {
	out := new(Summary)
	err := grpc.Invoke(ctx, "/summarizer.SummarizerService/Summarize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SummarizerService service

type SummarizerServiceServer interface {
	Summarize(context.Context, *SummarizerRequest) (*Summary, error)
}

func RegisterSummarizerServiceServer(s *grpc.Server, srv SummarizerServiceServer) {
	s.RegisterService(&_SummarizerService_serviceDesc, srv)
}

func _SummarizerService_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizerServiceServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/summarizer.SummarizerService/Summarize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizerServiceServer).Summarize(ctx, req.(*SummarizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SummarizerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "summarizer.SummarizerService",
	HandlerType: (*SummarizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Summarize",
			Handler:    _SummarizerService_Summarize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summarizer/summarizer.proto",
}

func init() { proto.RegisterFile("summarizer/summarizer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0xcd, 0xcd,
	0x4d, 0x2c, 0xca, 0xac, 0x4a, 0x2d, 0xd2, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x22, 0x4a, 0xaa, 0x5c, 0x82, 0xc1, 0x70, 0x5e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71,
	0x89, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88,
	0xa9, 0x24, 0xcb, 0xc5, 0x0e, 0x51, 0x56, 0x29, 0x24, 0xc4, 0xc5, 0x52, 0x92, 0x98, 0x5e, 0x2c,
	0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0x66, 0x1b, 0x85, 0x21, 0x9b, 0x12, 0x9c, 0x5a, 0x54,
	0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc8, 0xc5, 0x09, 0x17, 0x14, 0x92, 0xd5, 0x43, 0x72, 0x06, 0x86,
	0x8d, 0x52, 0xc2, 0x98, 0xd2, 0x95, 0x4a, 0x0c, 0x4e, 0xea, 0x51, 0xaa, 0xe9, 0x99, 0x25, 0x19,
	0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x49, 0x89, 0xf9, 0x05, 0x19, 0x89, 0xb9, 0xfa, 0xe9,
	0xf9, 0x60, 0x7f, 0x20, 0x79, 0x2c, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xdf, 0xcd, 0xf0, 0xf8, 0x00, 0x00, 0x00,
}
